import Link from 'next/link';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Globe,
  Star,
  Award,
  TrendingUp,
  Trash2,
  Book,
  FileText,
  Link as LinkIcon,
  Pencil,
} from 'lucide-react';
import type { Deck, Flashcard } from '@/types';

// Mock data fetching functions - in a real app, these would fetch from a database
async function getDeckDetails(deckId: string): Promise<Deck | null> {
  const mockDecks: Record<string, Deck> = {
    '1': {
      id: '1',
      title: 'JavaScript Fundamentals',
      description:
        'Master the basics of JavaScript programming with essential concepts and syntax.',
      category: 'Programming',
      author: 'User',
      size: 20,
      bibliography: ['"JavaScript: The Good Parts" by Douglas Crockford'],
    },
    '2': {
      id: '2',
      title: 'React Essentials',
      description:
        'Learn the core concepts of React including components, props, state, and hooks.',
      category: 'Programming',
      author: 'User',
      size: 25,
      bibliography: ['Official React Documentation'],
    },
    '3': {
      id: '3',
      title: 'Web Development Basics',
      description:
        'Fundamental concepts every web developer should know about HTML, CSS, and web technologies.',
      category: 'Web Development',
      author: 'User',
      size: 30,
      bibliography: [],
    },
    'gen-12345': {
      id: 'gen-12345',
      title:
        'Plan de Estudio: Estado del Arte en IA para Segmentación de Tumores Renales',
      description:
        'Plan de estudio para comprender el estado del arte en el uso de la Inteligencia Artificial para la segmentación de tumores renales, incluyendo aspectos multimodales, optimización y despliegue en hardware.',
      category: 'AI',
      author: 'AI',
      size: 15,
      bibliography: [],
    },
  };

  if (mockDecks[deckId]) {
    return mockDecks[deckId];
  }

  // Fallback for generated decks that might not be in the hardcoded list
  if (deckId.startsWith('gen-')) {
    return {
      id: deckId,
      title: 'AI Generated Deck',
      description: 'A deck generated by our AI.',
      category: 'Generated',
      author: 'AI',
      size: 15,
      bibliography: [],
    };
  }
  return null;
}

const sessions = [
  { day: 'Día 1', topic: 'Variables', type: 'Opción Múltiple', status: 'Completada', link: '#' },
  { day: 'Día 2', topic: 'Funciones', type: 'Tutor AI', status: 'Continuar', link: '#' },
  { day: 'Día 3', topic: 'Funciones', type: 'Quiz de repaso', status: 'Desbloquear en 1 día', link: '#', disabled: true },
];

const knowledgeAtoms = [
    { id: '1', name: 'Variables', description: 'Las variables son contenedores para almacenar...', source: 'Fuente' },
    { id: '2', name: 'Funciones', description: 'Las funciones son bloques de código diseñados para...', source: 'Fuente' },
    { id: '3', name: 'Bucles', description: 'Los bucles pueden ejecutar un bloque de código...', source: 'Fuente' },
];

const sources = [
    { id: '1', name: 'Javascript en el mundo', type: 'Libro', icon: <Book className="h-4 w-4" /> },
    { id: '2', name: 'Por qué Javascript es mejor', type: 'Posts de blog', icon: <FileText className="h-4 w-4" /> },
];

export default async function DeckDetailsPage({
  params: { deckId },
}: {
  params: { deckId: string };
}) {
  const deck = await getDeckDetails(deckId);

  if (!deck) {
    return (
      <div className="container mx-auto py-8 text-center">
        <h1 className="text-2xl font-bold">Deck not found</h1>
        <p className="text-muted-foreground">
          The requested deck could not be found.
        </p>
      </div>
    );
  }

  return (
    <div className="container mx-auto py-8">
      <div className="bg-card/50 p-6 sm:p-8 rounded-xl shadow-lg border">
        {/* Header */}
        <header className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <Globe className="h-8 w-8 text-primary" />
            <h1 className="text-3xl sm:text-4xl font-bold">{deck.title}</h1>
          </div>
          <Badge variant="outline" className="border-dashed">{deck.category}</Badge>
        </header>

        {/* Stats */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-10">
          <Card className="bg-card/70">
            <CardContent className="p-4 flex flex-col items-center justify-center text-center">
              <p className="text-muted-foreground mb-2 text-sm">Mejor Racha</p>
              <div className="flex items-center gap-2">
                <Star className="h-5 w-5 text-yellow-400" />
                <p className="text-2xl font-bold">1</p>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-card/70">
            <CardContent className="p-4 flex flex-col items-center justify-center text-center">
              <p className="text-muted-foreground mb-2 text-sm">CC ganados</p>
               <div className="flex items-center gap-2">
                <Award className="h-5 w-5 text-green-400" />
                <p className="text-2xl font-bold">5</p>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-card/70">
            <CardContent className="p-4 flex flex-col items-center justify-center text-center">
              <p className="text-muted-foreground mb-2 text-sm">Dominio del tema</p>
               <div className="flex items-center gap-2">
                 <TrendingUp className="h-5 w-5 text-blue-400" />
                <p className="text-2xl font-bold">10%</p>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Sessions */}
        <section className="mb-10">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-2xl font-bold">Sesiones</h2>
            <Button variant="outline">Ver plan completo</Button>
          </div>
          <Card className="bg-card/70">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Sesión</TableHead>
                  <TableHead>Tema</TableHead>
                  <TableHead>Tipo</TableHead>
                  <TableHead className="text-right">Estado</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {sessions.map((session, index) => (
                  <TableRow key={index}>
                    <TableCell>{session.day}</TableCell>
                    <TableCell>{session.topic}</TableCell>
                    <TableCell>{session.type}</TableCell>
                    <TableCell className="text-right">
                      <Button asChild variant={session.status === 'Completada' ? 'link' : 'default'} size="sm" disabled={session.disabled}>
                        <Link href={session.link} className={session.disabled ? 'text-muted-foreground' : ''}>{session.status}</Link>
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </Card>
        </section>

        {/* Knowledge Atoms */}
        <section className="mb-10">
           <div className="flex justify-between items-center mb-4">
              <h2 className="text-2xl font-bold">Átomos de conocimiento</h2>
              <Button variant="outline">Ver todos ({deck.size})</Button>
           </div>
           <Card className="bg-card/70">
            <Table>
                <TableBody>
                    {knowledgeAtoms.map(atom => (
                        <TableRow key={atom.id}>
                            <TableCell className="font-medium">{atom.name}</TableCell>
                            <TableCell className="text-muted-foreground">{atom.description}</TableCell>
                            <TableCell>
                                <Button variant="link" className="p-0 h-auto flex items-center gap-1">
                                    <LinkIcon className="h-3 w-3" /> {atom.source}
                                </Button>
                            </TableCell>
                            <TableCell>
                                <Button variant="link" className="p-0 h-auto">Ver</Button>
                            </TableCell>
                            <TableCell>
                                <Button variant="ghost" size="icon">
                                    <Pencil className="h-4 w-4" />
                                </Button>
                            </TableCell>
                            <TableCell>
                                <Button variant="ghost" size="icon" className="text-destructive hover:text-destructive">
                                    <Trash2 className="h-4 w-4" />
                                </Button>
                            </TableCell>
                        </TableRow>
                    ))}
                </TableBody>
            </Table>
           </Card>
        </section>

        {/* Sources */}
        <section>
          <h2 className="text-2xl font-bold mb-4">Fuentes</h2>
          <Card className="bg-card/70">
            <Table>
                <TableBody>
                    {sources.map(source => (
                       <TableRow key={source.id}>
                           <TableCell className="flex items-center gap-2">
                               {source.icon}
                               <span className="font-medium">{source.name}</span>
                           </TableCell>
                           <TableCell className="text-muted-foreground">{source.type}</TableCell>
                            <TableCell>
                                <Button variant="link" className="p-0 h-auto">Ver</Button>
                            </TableCell>
                            <TableCell>
                                <Button variant="ghost" size="icon" className="text-destructive hover:text-destructive">
                                    <Trash2 className="h-4 w-4" />
                                </Button>
                            </TableCell>
                       </TableRow>
                    ))}
                </TableBody>
            </Table>
          </Card>
        </section>
      </div>
    </div>
  );
}
